/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminforApproving;

import LoginandRegister.LoginForm;
import static LoginandRegister.RegisterForm.passwordHash;
import config.dbConnector;
import config.session;
import displayadmin.displayadmin;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sofia
 */
public class Admindash extends javax.swing.JFrame {

    /**
     * Creates new form Admindash
     */
    public Admindash() {
        initComponents();
        table_load();
    }
    
    public void table_load(){
         
         dbConnector dbc = new dbConnector();
    
        try {
            
        
            DefaultTableModel dt = (DefaultTableModel) showtbl.getModel();
            dt.setRowCount(0);
            
            String query = ("SELECT * FROM users");
            ResultSet rs = dbc.getData(query);
            
            while(rs.next()){
            
                Vector v = new Vector();
                
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));
         
                
                
                dt.addRow(v);
            
            }
       
        
        }catch (SQLException e){
            
            System.out.println(e);
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Display_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        displayadmin = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p_search_tbl = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        reglast = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        regfirst = new javax.swing.JTextField();
        regmid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        regadd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        regemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        regcontact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        accnt_type = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reguser = new javax.swing.JTextField();
        newpassw = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uid = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        Display_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Name", "Frist Name", "Middle Name", "Address", "Email", "Contact Number", "Gender", "Account Type", "Username", "Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showtbl);

        javax.swing.GroupLayout Display_panelLayout = new javax.swing.GroupLayout(Display_panel);
        Display_panel.setLayout(Display_panelLayout);
        Display_panelLayout.setHorizontalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
        );
        Display_panelLayout.setVerticalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        jPanel1.add(Display_panel);
        Display_panel.setBounds(10, 500, 1260, 200);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 10, 94, 30);

        displayadmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        displayadmin.setForeground(new java.awt.Color(255, 255, 255));
        displayadmin.setText("Admin");
        jPanel2.add(displayadmin);
        displayadmin.setBounds(160, 10, 230, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search : ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(780, 10, 100, 30);

        p_search_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p_search_tblKeyReleased(evt);
            }
        });
        jPanel2.add(p_search_tbl);
        p_search_tbl.setBounds(880, 10, 250, 30);

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Log-out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1169, 10, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Peach and Orange Creative Illustrated Abstract Pizza Boxcar Presentation (1).png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 0, 1080, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-account-48.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 0, 48, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Peach and Orange Creative Illustrated Abstract Pizza Boxcar Presentation (1).png"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(-390, 0, 790, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1270, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Last Name : ");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 60, 140, 30);

        reglast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(reglast);
        reglast.setBounds(30, 90, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("First Name : ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(340, 60, 130, 30);

        regfirst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(regfirst);
        regfirst.setBounds(340, 90, 200, 30);

        regmid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(regmid);
        regmid.setBounds(590, 90, 290, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Address :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 130, 170, 30);

        regadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regaddActionPerformed(evt);
            }
        });
        jPanel3.add(regadd);
        regadd.setBounds(30, 160, 510, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(590, 130, 160, 30);

        regemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regemailActionPerformed(evt);
            }
        });
        jPanel3.add(regemail);
        regemail.setBounds(590, 160, 290, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Contact Number :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 200, 170, 30);

        regcontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regcontactActionPerformed(evt);
            }
        });
        jPanel3.add(regcontact);
        regcontact.setBounds(30, 230, 270, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Gender :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(340, 200, 150, 30);

        gen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(gen);
        gen.setBounds(340, 230, 200, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Account Type :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(590, 200, 150, 30);

        accnt_type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accnt_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Owner", "Cashier" }));
        jPanel3.add(accnt_type);
        accnt_type.setBounds(590, 230, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Username :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(930, 130, 170, 30);

        reguser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(reguser);
        reguser.setBounds(930, 160, 270, 30);

        newpassw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswActionPerformed(evt);
            }
        });
        jPanel3.add(newpassw);
        newpassw.setBounds(930, 230, 270, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Users ID : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 20, 110, 30);

        uid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uid.setText("ID");
        jPanel3.add(uid);
        uid.setBounds(150, 20, 40, 30);

        status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Pending" }));
        jPanel3.add(status);
        status.setBounds(930, 90, 270, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Status :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(930, 60, 150, 30);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(840, 320, 170, 50);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(170, 320, 170, 50);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(620, 320, 170, 50);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(390, 320, 170, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Middle Name : ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(590, 60, 140, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Password :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(930, 200, 170, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 70, 1260, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showtblMouseClicked
        // click
        
        
       
       int r = showtbl.getSelectedRow();
        
        String id = showtbl.getValueAt(r, 0).toString();
        String lastname = showtbl.getValueAt(r, 1).toString();
        String firstname = showtbl.getValueAt(r, 2).toString();
        String middlename = showtbl.getValueAt(r, 3).toString();
        String address = showtbl.getValueAt(r, 4).toString();
        String email = showtbl.getValueAt(r, 5).toString();
        String contactnumber = showtbl.getValueAt(r, 6).toString();
        String gender = showtbl.getValueAt(r, 7).toString();
        String account_type = showtbl.getValueAt(r, 8).toString();
        String usernames = showtbl.getValueAt(r, 9).toString();
        String passwords = showtbl.getValueAt(r, 10).toString();
        String stat = showtbl.getValueAt(r, 11).toString();
                
        
        uid.setText(id);
        reglast.setText(lastname);
        regfirst.setText(firstname);
        regmid.setText(middlename);
        regadd.setText(address);
        regemail.setText(email);
        regcontact.setText(contactnumber);
        gen.setSelectedItem(gender);
        accnt_type.setSelectedItem(account_type);
        reguser.setText(usernames);
       
        status.setSelectedItem(stat);
            
                
        
        
     
            
    }//GEN-LAST:event_showtblMouseClicked

    private void regaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regaddActionPerformed

    private void regemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regemailActionPerformed

    private void regcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regcontactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // delete btn
        
        String userid = uid.getText();
         
         dbConnector dbc = new dbConnector();
        
        try{
            if(dbc.deleteData("DELETE FROM users WHERE id = '"+userid+"' ")){
            
                JOptionPane.showMessageDialog(null, "Data Deleted");
            }
              
            
        } catch (Exception e){
            
            System.out.println(e);

        }
        
         uid.setText("");
       reglast.setText("");
        regfirst.setText("");
         regmid.setText("");
           regadd.setText("");
            regemail.setText("");
            regcontact.setText("");
            gen.setSelectedItem("");
           accnt_type.setSelectedItem("");
            reguser.setText("");
            newpassw.setText("");
            status.setSelectedItem("");
        table_load();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // clear btn
        
         uid.setText("");
       reglast.setText("");
        regfirst.setText("");
         regmid.setText("");
           regadd.setText("");
            regemail.setText("");
            regcontact.setText("");
            gen.setSelectedItem("");
           accnt_type.setSelectedItem("");
            reguser.setText("");
            newpassw.setText("");
            status.setSelectedItem("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Update btn
        
    
        
        String ids = uid.getText();
        String lastnames = reglast.getText();
        String firstnames = regfirst.getText();
        String middlenames = regmid.getText();  
        String addresss = regadd.getText();
        String emails = regemail.getText();
        String contactnum = regcontact.getText();
        String genders = gen.getSelectedItem().toString();
        String account_types = accnt_type.getSelectedItem().toString();
        String usernamess = reguser.getText();
        String passwordss = newpassw.getText();
        String Stat = status.getSelectedItem().toString();
        
        
        
            try {
            dbConnector dbc = new dbConnector();
            
            String newPassword = passwordss; 
            if (!newPassword.isEmpty()) {
            newPassword = passwordHash(newPassword);
            }

            String query = "UPDATE users SET lastname ='" + lastnames + "', "
                + "firstname ='" + firstnames + "', middlename ='" + middlenames + "',"
                + " address ='" + addresss + "', email ='" + emails + "', "
                + " contactnumber ='" + contactnum + "', gender ='" + genders + "',"
                + " account_type ='" + account_types + "', username ='" + usernamess + "',"
                + " Status ='" + Stat + "'";

            if (!passwordss.isEmpty()) {
            query += ", password ='" + newPassword + "'";
            }

            query += " WHERE id ='" + ids + "'";

            if (dbc.insertData(query)) {
            JOptionPane.showMessageDialog(null, "Data Updated");
            }

            } catch (Exception e) {
            System.out.println(e);
            }
        
         uid.setText("");
       reglast.setText("");
        regfirst.setText("");
         regmid.setText("");
           regadd.setText("");
            regemail.setText("");
            regcontact.setText("");
            gen.setSelectedItem("");
           accnt_type.setSelectedItem("");
            reguser.setText("");
            newpassw.setText("");
            status.setSelectedItem("");
        table_load();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // add btn

        String Stat = status.getSelectedItem().toString();
        
        dbConnector dbc = new dbConnector();
        
        try{
            
            if(dbc.insertData("INSERT INTO users(lastname, firstname, middlename, address, email, contactnumber, gender, account_type, username, password, status)"
                + "Values ('"+reglast.getText()+"', '"+regfirst.getText()+"', '"+regmid.getText()+"', '"+regadd.getText()+"', '"+regemail.getText()+"',"
                + " '"+regcontact.getText()+"', '"+gen.getSelectedItem()+"', '"+accnt_type.getSelectedItem()+"', '"+reguser.getText()+"', '"+newpassw.getText()+"',"
                + " '"+Stat+"')")){
                JOptionPane.showMessageDialog(null, "Data Added");
        
            }else{
            
                JOptionPane.showMessageDialog(null, "Connection Error");
        } 
        }catch (HeadlessException e){
        
            System.out.println(e);
        
        }
        
         uid.setText("");
       reglast.setText("");
        regfirst.setText("");
         regmid.setText("");
           regadd.setText("");
            regemail.setText("");
            regcontact.setText("");
            gen.setSelectedItem("");
           accnt_type.setSelectedItem("");
            reguser.setText("");
            newpassw.setText("");
            status.setSelectedItem("");
        
        table_load();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void p_search_tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_search_tblKeyReleased
        // TODO add your handling code here:
        
        String name = p_search_tbl.getText();
        
        dbConnector dbc = new dbConnector();

        try {

            DefaultTableModel dt = (DefaultTableModel) showtbl.getModel();
            dt.setRowCount(0);

            String query = ("SELECT * FROM users WHERE lastname LIKE '%"+name+"%' ");
            ResultSet rs = dbc.getData(query);
   

            while(rs.next()){

                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));

                dt.addRow(v);

            }

        }catch (Exception e){
            table_load();

        }
    }//GEN-LAST:event_p_search_tblKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // lgout btn
        JOptionPane.showMessageDialog(null, "Log-out Successfully");
        LoginForm log = new LoginForm();
        log.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void newpasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        
        this.dispose();

        String last = displayadmin.getText();

        dbConnector dbc = new dbConnector();

        try{

            String query =("SELECT * FROM users WHERE lastname ='"+last+"' ");
            ResultSet rs = dbc.getData(query);

            if(rs.next()){

                displayadmin dis = new displayadmin();
                dis.display_id.setText(rs.getString("id"));
                dis.reglast.setText(rs.getString("lastname"));
                dis.regfirst.setText(rs.getString("firstname"));
                dis.regmid.setText(rs.getString("middlename"));
                dis.regadd.setText(rs.getString("address"));
                dis.regcontact.setText(rs.getString("contactnumber"));
                dis.regemail.setText(rs.getString("email"));
                dis.gen2.setText("gender");

                dis.setVisible(true);

            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
         session sess = session.getInstance();
        int user_id = sess.getId();
        
        if(user_id == 0){
            JOptionPane.showMessageDialog(null, "No Account, Login First!");
            LoginForm log = new LoginForm();
            log.setVisible(true);
            this.dispose();
        }else{
            displayadmin.setText(""+sess.getLast());
        }
       
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admindash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display_panel;
    private javax.swing.JComboBox<String> accnt_type;
    public javax.swing.JLabel displayadmin;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newpassw;
    private javax.swing.JTextField p_search_tbl;
    private javax.swing.JTextField regadd;
    private javax.swing.JTextField regcontact;
    private javax.swing.JTextField regemail;
    private javax.swing.JTextField regfirst;
    private javax.swing.JTextField reglast;
    private javax.swing.JTextField regmid;
    private javax.swing.JTextField reguser;
    private javax.swing.JTable showtbl;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
