/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sofia
 */
public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        displaydata();
    }
    
    public void displaydata(){
        
        try{
            dbConnector dbc = new dbConnector();
            
            DefaultTableModel dt = (DefaultTableModel) showtbl.getModel();
            dt.setRowCount(0);
                ResultSet rs = dbc.getData("SELECT id,lastname,firstname,"
                            + "middlename,address,email,"
                                + "contactnumber,gender,status "
                                    + "FROM users WHERE account_type ='Cashier' ");
                                        showtbl.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(SQLException e){
            System.out.println(""+e);
        
        }
    
    
    
    }
    
    
//    public void table_load(){
//         
//         dbConnector dbc = new dbConnector();
//    
//        try {
//            
//        
//            DefaultTableModel dt = (DefaultTableModel) showtbl.getModel();
//            dt.setRowCount(0);
//            
//            String query = ("SELECT id,lastname,firstname,"
//                            + "middlename,address,email,"
//                                + "contactnumber,gender,status "
//                                    + "FROM users WHERE account_type ='Cashier' ");
//            ResultSet rs = dbc.getData(query);
//            
//            while(rs.next()){
//            
//                Vector v = new Vector();
//                
//                v.add(rs.getString(1));
//                v.add(rs.getString(2));
//                v.add(rs.getString(3));
//                v.add(rs.getString(4));
//                v.add(rs.getString(5));
//                v.add(rs.getString(6));
//                v.add(rs.getString(7));
//                v.add(rs.getString(8));
//                v.add(rs.getString(9));
//                        
//                
//                dt.addRow(v);
//            
//            }
//       
//        
//        }catch (SQLException e){
//            
//            System.out.println(e);
//        
//        }
//    
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtbl = new javax.swing.JTable();

        jPanel1.setMaximumSize(new java.awt.Dimension(1030, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 600));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Employee Details:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(12, 13, 161, 34);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1000, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Name", "Frist Name", "Middle Name", "Address", "Email", "Contact Number", "Gender", "Status"
            }
        ));
        showtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showtbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 80, 1000, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showtblMouseClicked
        // click
      
    }//GEN-LAST:event_showtblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showtbl;
    // End of variables declaration//GEN-END:variables
}
