/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginandRegister;

import AdminforApproving.Admindash;
import Cashier.CashierDash;
import static LoginandRegister.RegisterForm.passwordHash;
import Owner.OwnerDash;
import config.dbConnector;
import config.session;
import displayuserinfo.displayuser;
import java.awt.Color;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }
    static String last;
    static String statusss;
    static String typess;
    static String first;
    static String middle;
    static String adds;
    static String contac;
    static String email_add;
    static String gender_m;
    static String user_name;
    static String pass_word;
    static String confirm_password;
    
    
    
     public static boolean loginAcc(String username1, String password1){
        dbConnector connector = new dbConnector();
        
        try{
            String hashedPassword = passwordHash(password1);
            String query = "SELECT * FROM users WHERE username ='"+username1+"' "
                    + "AND password ='"+hashedPassword+"' AND status ='Active' ";
            ResultSet resultSet = connector.getData(query);
            
            if(resultSet.next()){
                
                statusss = resultSet.getString("status");
                typess = resultSet.getString("account_type");            
                
                 session sess = session.getInstance(); 
                 
                 sess.setId(resultSet.getInt("id"));
                 sess.setLast(resultSet.getString("lastname"));
                 sess.setFirst(resultSet.getString("firstname"));
                 sess.setMiddle(resultSet.getString("middlename"));
                 sess.setAdds(resultSet.getString("address"));
                 sess.setEmail_add(resultSet.getString("email"));
                 sess.setContac(resultSet.getString("contactnumber"));
                 sess.setGender_m(resultSet.getString("gender"));
                 sess.setTypess(resultSet.getString("account_type"));
                 sess.setUser_name(resultSet.getString("username"));
                 sess.setStatusss(resultSet.getString("status"));

                return true;
            
            }else{
                return false;
            }
        }catch(SQLException e){
        return false;
        }
    
    }
    
    public static boolean isAdmin(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM users WHERE username ='" + username + "' AND account_type ='Admin'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    
    public static boolean isOwner(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM users WHERE username ='" + username + "' AND account_type ='Owner'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    
    public static boolean isCashier(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM users WHERE username ='" + username + "' AND account_type ='Cashier'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    
    public static boolean isPending(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM users WHERE username ='" + username + "' AND status ='Pending'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        showpass = new javax.swing.JCheckBox();
        loginbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 660));
        setPreferredSize(new java.awt.Dimension(450, 660));
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 430, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 270, 90, 20);
        jPanel1.add(user);
        user.setBounds(180, 260, 170, 40);

        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass);
        showpass.setBounds(250, 380, 130, 29);

        loginbutton.setText("Login");
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        loginbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginbuttonKeyPressed(evt);
            }
        });
        jPanel1.add(loginbutton);
        loginbutton.setBounds(280, 430, 130, 40);

        jButton1.setText("Create new account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 480, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 340, 100, 20);
        jPanel1.add(pass);
        pass.setBounds(180, 330, 170, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Orange and Black Bold Delicious Pizza Mobile Video.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        
        session sess = session.getInstance(); 
        String username = user.getText();
        
        if (loginAcc(user.getText(), pass.getText())) {      
        if (isAdmin(username)) {
            JOptionPane.showMessageDialog(null, "Login Successfully as Admin");
            Admindash ad = new Admindash();
            ad.displayadmin.setText(""+sess.getLast());
            ad.setVisible(true);
            this.dispose();
        } else if (isOwner(username)) {
            JOptionPane.showMessageDialog(null, "Login Successfully as Owner");
            OwnerDash own = new OwnerDash();
            own.ownerdisplay.setText(""+last);
            own.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Login Successfully as Cashier");
            CashierDash cash = new CashierDash();
            cash.cashierdisplay.setText(""+sess.getLast());
            cash.cashierdisplayfirst.setText(""+sess.getFirst());
            cash.setVisible(true);
            this.dispose();   
        }
        this.dispose(); 
        } else if(isPending(username)){
            JOptionPane.showMessageDialog(null, "Contact Admin to Activate your Account!");     
        }else {
            JOptionPane.showMessageDialog(null, "Invalid Password");
        } 
        
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        RegisterForm reg = new RegisterForm();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        
        if (showpass.isSelected()){
            pass.setEchoChar((char)0);
        }else{
            pass.setEchoChar('*');

        }
    }//GEN-LAST:event_showpassActionPerformed

    private void loginbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginbuttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonKeyPressed

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        // TODO add your handling code here:
        
        loginbutton.setBackground(Color.GREEN);
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        // TODO add your handling code here:
        
        loginbutton.setBackground(Color.white);
    }//GEN-LAST:event_loginbuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private static javax.swing.JPasswordField pass;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
