/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Owner;

import LoginandRegister.LoginForm;
import Panels.Employee;
import Panels.Product;
import Panels.Reports;
import config.dbConnector;
import config.session;
import displayuserinfo.displayuser;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import panelloader.JpanelLoader;




public class OwnerDash extends javax.swing.JFrame {

    JpanelLoader jpload = new JpanelLoader();
    
    public OwnerDash() {
        initComponents();
    }
    

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ownerdisplay = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Display_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-basket-25.png"))); // NOI18N
        jButton2.setText("Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 120, 159, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-reports-25.png"))); // NOI18N
        jButton4.setText("Reports");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 420, 159, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-employee-25.png"))); // NOI18N
        jButton1.setText("Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 270, 159, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-log-out-25.png"))); // NOI18N
        jButton3.setText("Sign-out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 560, 159, 100);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(109, 21, 94, 22);

        ownerdisplay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ownerdisplay.setForeground(new java.awt.Color(255, 255, 255));
        ownerdisplay.setText("Owner");
        jPanel2.add(ownerdisplay);
        ownerdisplay.setBounds(213, 21, 270, 22);

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Log-out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1169, 10, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Peach and Orange Creative Illustrated Abstract Pizza Boxcar Presentation (1).png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 0, 1080, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-account-48.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 48, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Peach and Orange Creative Illustrated Abstract Pizza Boxcar Presentation (1).png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(-390, 0, 790, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1260, 70);

        Display_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout Display_panelLayout = new javax.swing.GroupLayout(Display_panel);
        Display_panel.setLayout(Display_panelLayout);
        Display_panelLayout.setHorizontalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        Display_panelLayout.setVerticalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jPanel1.add(Display_panel);
        Display_panel.setBounds(240, 100, 1030, 600);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 110, 1080, 610);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 110, 1080, 610);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 0, 1080, 610);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1080, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // lgout btn
        JOptionPane.showMessageDialog(null, "Log-out Successfully");
        LoginForm log = new LoginForm();
        log.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

        
        String last = ownerdisplay.getText();

        dbConnector dbc = new dbConnector();

        try{

            String query =("SELECT * FROM users WHERE lastname ='"+last+"' ");
            ResultSet rs = dbc.getData(query);

            if(rs.next()){

                displayuser dis = new displayuser();
                dis.display_id.setText(rs.getString("id"));
                dis.reglast.setText(rs.getString("lastname"));
                dis.regfirst.setText(rs.getString("firstname"));
                dis.regmid.setText(rs.getString("middlename"));
                dis.regadd.setText(rs.getString("address"));
                dis.regcontact.setText(rs.getString("contactnumber"));
                dis.regemail.setText(rs.getString("email"));
                dis.gen2.setText("gender");
                
                dis.setVisible(true);

            }

        }catch(Exception e){

        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Reports btn
        Reports rep = new Reports();
        jpload.jPanelLoader(Display_panel, rep);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Log-out Successfully");
        LoginForm log = new LoginForm();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //prdocut btn

        Product prod = new Product();
        jpload.jPanelLoader(Display_panel, prod);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //employee btn
        Employee emp = new Employee();
        jpload.jPanelLoader(Display_panel, emp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
         session sess = session.getInstance();
        int user_id = sess.getId();
        
        if(user_id == 0){
            JOptionPane.showMessageDialog(null, "No Account, Login First!");
            LoginForm log = new LoginForm();
            log.setVisible(true);
            this.dispose();
        }else{
            ownerdisplay.setText(""+sess.getLast());
        }
      
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel ownerdisplay;
    // End of variables declaration//GEN-END:variables
}
