/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package displayowner;

import displayadmin.*;
import AdminforApproving.Admindash;
import displayuserinfo.*;
import Cashier.CashierDash;
import LoginandRegister.LoginForm;
import static LoginandRegister.RegisterForm.passwordHash;
import Owner.OwnerDash;
import config.dbConnector;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia
 */
public class updatepassowner extends javax.swing.JFrame {

    /**
     * Creates new form updatepass
     */
    public updatepassowner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        reguser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        regpass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        regconfirmpass = new javax.swing.JPasswordField();
        spass1 = new javax.swing.JCheckBox();
        spass2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        display_id = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Username :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 170, 30);

        reguser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(reguser);
        reguser.setBounds(210, 120, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Password :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 160, 170, 30);
        jPanel1.add(regpass);
        regpass.setBounds(210, 160, 200, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Confirm Password :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 220, 210, 30);
        jPanel1.add(regconfirmpass);
        regconfirmpass.setBounds(210, 220, 200, 30);

        spass1.setText("Show Password");
        spass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spass1ActionPerformed(evt);
            }
        });
        jPanel1.add(spass1);
        spass1.setBounds(320, 190, 140, 23);

        spass2.setText("Show Password");
        spass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spass2ActionPerformed(evt);
            }
        });
        jPanel1.add(spass2);
        spass2.setBounds(320, 250, 140, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-return-25.png"))); // NOI18N
        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 10, 30, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("ID NO: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 30, 80, 20);

        display_id.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        display_id.setText("D ID");
        jPanel1.add(display_id);
        display_id.setBounds(110, 30, 80, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Update Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 310, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spass1ActionPerformed
        // TODO add your handling code here:

        if (spass1.isSelected()){
            regpass.setEchoChar((char)0);
        }else{
            regpass.setEchoChar('*');

        }
    }//GEN-LAST:event_spass1ActionPerformed

    private void spass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spass2ActionPerformed
        // TODO add your handling code here:
        if (spass2.isSelected()){
            regconfirmpass.setEchoChar((char)0);
        }else{
            regconfirmpass.setEchoChar('*');

        }
    }//GEN-LAST:event_spass2ActionPerformed

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6AncestorAdded

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.dispose();
        OwnerDash ad = new OwnerDash();
            ad.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String idss = display_id.getText();
        String usernamess = reguser.getText();
        

        dbConnector dbc = new dbConnector();

        try{
            
            String password = passwordHash(regpass.getText());

            if(dbc.insertData("UPDATE users SET username ='"+usernamess+"',"
                + " password ='"+password+"'  WHERE id ='"+idss+"' ")){

            JOptionPane.showMessageDialog(null, "Data Updated Please Login Again!");
            this.dispose();
            LoginForm ads = new LoginForm();
            ads.setVisible(true);
        }

        } catch (Exception e){

            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatepassowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatepassowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatepassowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatepassowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatepassowner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel display_id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField regconfirmpass;
    public javax.swing.JPasswordField regpass;
    public javax.swing.JTextField reguser;
    private javax.swing.JCheckBox spass1;
    private javax.swing.JCheckBox spass2;
    // End of variables declaration//GEN-END:variables
}
